# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
before:
  hooks:
    - go mod download

builds:
  - binary: 'pulumi-resource-neon'
    ldflags:
      - '-s -w -X github.com/kislerdm/pulumi-neon/provider.Version={{.Version}}'

    env:
      - CGO_ENABLED=0n

    goos:
      - windows
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: 'pulumi-resource-neon-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: 'pulumi-resource-neon-v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'schema.json'

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'LICENSE'
    - glob: 'schema.json'

changelog:
  disable: true
