// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiSdk.Neon
{
    [NeonResourceType("pulumi:providers:neon")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Neon API token.
        /// </summary>
        [Output("api_key")]
        public Output<string> Api_key { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("neon", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/kislerdm/pulumi-neon/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Neon API token.
        /// </summary>
        [Input("api_key", required: true)]
        public Input<string> Api_key { get; set; } = null!;

        public ProviderArgs()
        {
            Api_key = Utilities.GetEnv("NEON_API_KEY");
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
