"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Project = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, opts) {
        return new Project(name, undefined, Object.assign(Object.assign({}, opts), { id: id }));
    }
    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }
    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name, args, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["org_id"] = args ? args.org_id : undefined;
            resourceInputs["connection_uri"] = undefined /*out*/;
            resourceInputs["connection_uri_pooler"] = undefined /*out*/;
            resourceInputs["default_branch_name"] = undefined /*out*/;
            resourceInputs["default_database_name"] = undefined /*out*/;
            resourceInputs["default_endpoint_host"] = undefined /*out*/;
            resourceInputs["default_endpoint_host_pooler"] = undefined /*out*/;
            resourceInputs["default_role_name"] = undefined /*out*/;
            resourceInputs["default_role_password"] = undefined /*out*/;
            resourceInputs["identifier"] = undefined /*out*/;
        }
        else {
            resourceInputs["connection_uri"] = undefined /*out*/;
            resourceInputs["connection_uri_pooler"] = undefined /*out*/;
            resourceInputs["default_branch_name"] = undefined /*out*/;
            resourceInputs["default_database_name"] = undefined /*out*/;
            resourceInputs["default_endpoint_host"] = undefined /*out*/;
            resourceInputs["default_endpoint_host_pooler"] = undefined /*out*/;
            resourceInputs["default_role_name"] = undefined /*out*/;
            resourceInputs["default_role_password"] = undefined /*out*/;
            resourceInputs["identifier"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["org_id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}
exports.Project = Project;
/** @internal */
Project.__pulumiType = 'neon:resource:Project';
//# sourceMappingURL=project.js.map