"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
const __config = new pulumi.Config("neon");
Object.defineProperty(exports, "api_key", {
    get() {
        var _a;
        return (_a = __config.get("api_key")) !== null && _a !== void 0 ? _a : utilities.getEnv("NEON_API_KEY");
    },
    enumerable: true,
});
//# sourceMappingURL=vars.js.map