name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-24.04
    steps:
      - name: Define the version
        id: version
        uses: pulumi/provider-version-action@v1
    outputs:
      version: ${{ steps.version.outputs.version }}

  release:
      name: Build and release
      uses: pulumi/publish-go-binary-action/.github/workflows/build-binaries.yml@v1
      needs: version
      with:
        binary-name: pulumi-resource-neon
        packages: github.com/kislerdm/pulumi-neon/provider/cmd/pulumi-resource-neon
        version: ${{ needs.version.outputs.version }}
        version-path: github.com/kislerdm/pulumi-neon/provider.Version
        root-dir: provider
        build-args: '-ldflags="-s -w"'
        extra-package-files: LICENSE
        cgo-enabled: '0'
        runs-on: ubuntu-24.04
