name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release-provider:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'provider/go.mod'
          cache-dependency-path: 'provider/go.sum'
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Release provider
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          args: release --clean
          workdir: './provider'
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
