name: Tests
on:
  pull_request:
    paths:
      - 'provider/**'
      - 'sdk/go/**'
      - 'sdk/go.*'
      - 'schema.json'
  push:
    paths:
      - 'provider/**'
      - 'sdk/go/**'
      - 'sdk/go.*'
      - 'schema.json'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version-file: 'provider/go.mod'
#          cache-dependency-path: 'provider/go.sum'
#          cache: true
#      - run: cd provider && go mod download
#        name: Install dependencies
#      - name: Run linters
#        uses: golangci/golangci-lint-action@v6
#        with:
#          version: latest
#          working-directory: provider
#          args: "--timeout 5m -c ../.golangci.yml"

  tests:
    name: Tests
#    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'provider/go.mod'
          cache-dependency-path: 'provider/go.sum'
          cache: true
      - uses: pulumi/actions@v6
        with:
          pulumi-version: "3.142.0"
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap pulumi/tap
          brew install pulumictl
        name: Install pulumictl
      - run: make provider
        name: Build local provider
      - run: make test_provider
        name: Run Tests
        env:
          ACC_TEST: 1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          ORG_ID: ${{ vars.ORG_ID }}
